DROP FUNCTION IF EXISTS [FN_LAST_10_MATCHES];
GO
CREATE FUNCTION FN_LAST_10_MATCHES (@P_NAME VARCHAR(50)) RETURNS TABLE
AS 
RETURN
(
    SELECT TOP 10 * FROM [MATCH] 
    INNER JOIN [PLAYER] 
        ON [MATCH].PLAYER_ONE_ID = [PLAYER].PLAYER_ID
        OR
        [MATCH].[PLAYER_TWO_ID] = [PLAYER].PLAYER_ID
    WHERE [PLAYER].PLAYER_ID = @P_NAME
);
GO
