DROP FUNCTION IF EXISTS [FN_SELECT_BREAK_POINTS];
GO
CREATE FUNCTION FN_SELECT_BREAK_POINTS (@IPD_KEY VARCHAR(100)) RETURNS TABLE
AS
RETURN 
(   
    SELECT * FROM [IN_PLAY_DATA] WHERE
        [IN_PLAY_DATA_KEY] = @IPD_KEY AND
        ([IN_PLAY_DATA_SCORE] = '[*30-40]' OR
        [IN_PLAY_DATA_SCORE] = '[*15-40]' OR
        [IN_PLAY_DATA_SCORE] = '[*0-40]' OR
        [IN_PLAY_DATA_SCORE] = '[*40-A*]' OR
        [IN_PLAY_DATA_SCORE] = '[40-30*]' OR
        [IN_PLAY_DATA_SCORE] = '[40-15*]' OR
        [IN_PLAY_DATA_SCORE] = '[40-0*]' OR
        [IN_PLAY_DATA_SCORE] = '[A-40*]')
);
GO

SELECT * FROM FN_SELECT_BREAK_POINTS('Novak Djokovic Juan Martin Del Potro 2018-09-09');
SELECT COUNT(*) FROM FN_SELECT_BREAK_POINTS('Novak Djokovic Juan Martin Del Potro 2018-09-09'); 


